# Generated by Django 3.0.7 on 2021-04-17 17:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='username',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
