# Generated by Django 3.0.7 on 2021-04-17 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210417_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='retype_password',
        ),
    ]
