# Generated by Django 3.0.7 on 2021-04-19 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210418_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('no', models.IntegerField(null=True)),
                ('arrival', models.FloatField(null=True)),
                ('departure', models.FloatField(null=True)),
                ('sc', models.IntegerField(null=True)),
                ('sc_price', models.IntegerField(null=True)),
                ('first_ac', models.IntegerField(null=True)),
                ('first_price', models.IntegerField(null=True)),
                ('second_ac', models.IntegerField(null=True)),
                ('second_price', models.IntegerField(null=True)),
                ('third_ac', models.IntegerField(null=True)),
                ('third_price', models.IntegerField(null=True)),
                ('dest_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='des', to='app.Station')),
                ('dest_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Station')),
            ],
        ),
    ]
