# Generated by Django 3.0.7 on 2021-04-19 04:58

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_station_train'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='string',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
