# Generated by Django 3.0.7 on 2021-04-19 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_train_string'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='string',
        ),
    ]
