# Generated by Django 3.0.7 on 2021-04-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
