# Generated by Django 3.0.7 on 2021-04-20 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_detail_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='coach',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='pnr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='train',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Train'),
        ),
    ]
