# Generated by Django 3.0.7 on 2021-04-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_detail_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
