# Generated by Django 3.0.7 on 2021-04-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='book_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
