# Generated by Django 3.0.7 on 2021-04-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_detail_book_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='arrival',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='train',
            name='departure',
            field=models.TimeField(null=True),
        ),
    ]
